import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { apiService } from '../services/api';
import { ArrowLeft, Loader2, FileText, Printer, AlertTriangle, Shield, TrendingUp, Users, Clock, MapPin, Lightbulb, CheckCircle2 } from 'lucide-react';

export function ExecutiveBriefing() {
  const [briefing, setBriefing] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchBriefing = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await apiService.getExecutiveBriefing();
      if (response.success) {
        setBriefing(response.data);
      }
    } catch (err) {
      console.error('Error fetching executive briefing:', err);
      setError('Failed to generate executive briefing. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBriefing();
  }, []);

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-32">
        <Loader2 className="w-12 h-12 text-brand-400 animate-spin mb-4" />
        <p className="text-slate-400 text-sm">Agent 11 is compiling the executive briefing...</p>
        <p className="text-slate-500 text-xs mt-1">Analyzing tickets, SLA compliance, risk zones, and worker performance</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-md mx-auto text-center py-20">
        <AlertTriangle className="w-16 h-16 text-red-500 mx-auto mb-6" />
        <h2 className="text-xl font-bold text-slate-100">Briefing Unavailable</h2>
        <p className="text-slate-400 text-xs mt-2">{error}</p>
        <button onClick={fetchBriefing} className="mt-6 px-5 py-2 rounded-xl bg-brand-500 text-white text-sm font-bold">
          Retry
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6 print:space-y-4">
      {/* Header (hidden in print) */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 print:hidden">
        <div>
          <Link
            to="/dashboard"
            className="inline-flex items-center space-x-2 text-xs font-bold uppercase tracking-wider text-slate-500 hover:text-slate-300 transition-colors mb-2"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Dashboard</span>
          </Link>
          <h1 className="text-2xl font-extrabold text-slate-100 tracking-tight flex items-center gap-2">
            <FileText className="w-6 h-6 text-brand-400" />
            Executive Operations Briefing
          </h1>
          <p className="text-xs text-slate-500 mt-1">Generated by Agent 11 · {briefing?.generatedAt ? new Date(briefing.generatedAt).toLocaleString() : 'Now'}</p>
        </div>
        
        <div className="flex gap-2">
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-600 text-white text-xs font-bold shadow-lg transition-all"
          >
            <Printer className="w-4 h-4" />
            Export / Print
          </button>
          <button
            onClick={fetchBriefing}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-300 text-xs font-bold transition-all"
          >
            Regenerate
          </button>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 print:grid-cols-4">
        <div className="glass-panel rounded-2xl p-4 border border-slate-900">
          <div className="flex items-center gap-2 mb-2">
            <Shield className="w-4 h-4 text-red-400" />
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Critical</span>
          </div>
          <p className="text-2xl font-extrabold text-red-400">{briefing?.criticalCount || 0}</p>
        </div>
        <div className="glass-panel rounded-2xl p-4 border border-slate-900">
          <div className="flex items-center gap-2 mb-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">SLA Compliance</span>
          </div>
          <p className="text-2xl font-extrabold text-emerald-400">{briefing?.slaCompliancePercent || 0}%</p>
        </div>
        <div className="glass-panel rounded-2xl p-4 border border-slate-900 col-span-2">
          <div className="flex items-center gap-2 mb-2">
            <Lightbulb className="w-4 h-4 text-amber-400" />
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Top Recommendation</span>
          </div>
          <p className="text-xs text-slate-300 font-medium leading-relaxed">{briefing?.topRecommendation || 'No recommendations available.'}</p>
        </div>
      </div>

      {/* Main Report Body */}
      <div className="glass-panel rounded-3xl p-6 sm:p-8 border border-slate-900 shadow-xl print:shadow-none print:border-gray-300">
        <div className="prose prose-invert prose-sm max-w-none 
          prose-headings:text-slate-100 prose-headings:font-extrabold prose-headings:tracking-tight
          prose-h1:text-xl prose-h1:border-b prose-h1:border-slate-800 prose-h1:pb-3 prose-h1:mb-6
          prose-h2:text-base prose-h2:text-brand-400 prose-h2:mt-8 prose-h2:mb-3
          prose-h3:text-sm prose-h3:text-slate-300
          prose-p:text-slate-400 prose-p:leading-relaxed prose-p:text-xs
          prose-li:text-slate-400 prose-li:text-xs
          prose-strong:text-slate-200
          prose-blockquote:border-l-brand-500 prose-blockquote:bg-slate-950/40 prose-blockquote:rounded-xl prose-blockquote:p-3
          prose-hr:border-slate-900
          print:prose-headings:text-gray-900 print:prose-p:text-gray-700 print:prose-li:text-gray-700 print:prose-strong:text-gray-900
        ">
          <div dangerouslySetInnerHTML={{ __html: renderMarkdown(briefing?.report || '') }} />
        </div>
      </div>

      {/* Print-only footer */}
      <div className="hidden print:block text-center text-gray-500 text-xs mt-8 border-t border-gray-300 pt-4">
        <p>CivicSprint AI — Executive Operations Briefing</p>
        <p>Generated by Agent 11 (AI Executive Briefing Generator) · {new Date().toLocaleString()}</p>
        <p>Confidential — For Municipal Administration Use Only</p>
      </div>
    </div>
  );
}

// Simple markdown-to-HTML renderer for the report
function renderMarkdown(md) {
  if (!md) return '';
  return md
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^---$/gm, '<hr />')
    .replace(/^\> (.+)$/gm, '<blockquote>$1</blockquote>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/gm, (match) => `<ul>${match}</ul>`)
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br />')
    .replace(/^(.+)$/gm, (line) => {
      if (line.startsWith('<')) return line;
      return line;
    });
}

export default ExecutiveBriefing;
